// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReenWise.Infrastructure.Data.Context;

namespace ReenWise.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ReenWiseDbContext))]
    [Migration("20200114151758_InitialModel")]
    partial class InitialModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ReenWise.Domain.Models.Mirror.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasMaxLength(128);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(32)")
                        .HasMaxLength(32);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)")
                        .HasMaxLength(32);

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("ReenWise.Domain.Models.Mirror.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasMaxLength(128);

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<Guid?>("InitialOperatingHoursId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ManufacturerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(1024)")
                        .HasMaxLength(1024);

                    b.Property<Guid?>("OperatingHoursId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(32)")
                        .HasMaxLength(32);

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InitialOperatingHoursId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("ModelId");

                    b.HasIndex("OperatingHoursId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("UnitId");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("ReenWise.Domain.Models.Mirror.LicensePlate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasMaxLength(128);

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(8)")
                        .HasMaxLength(8);

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("LicensePlates");
                });

            modelBuilder.Entity("ReenWise.Domain.Models.Mirror.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasMaxLength(128);

                    b.Property<float?>("AccuracyRadius")
                        .HasColumnType("real");

                    b.Property<int?>("Course")
                        .HasColumnType("int");

                    b.Property<Guid?>("EquipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("InMovement")
                        .HasColumnType("bit");

                    b.Property<float>("Latitude")
                        .HasColumnType("real");

                    b.Property<float>("Longitude")
                        .HasColumnType("real");

                    b.Property<string>("SignalSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Speed")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("ReenWise.Domain.Models.Mirror.Manufacturer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.ToTable("Manufacturers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ab176dde-08f9-4c31-92be-d3e58adf07f8"),
                            Name = "Nordcon AS"
                        },
                        new
                        {
                            Id = new Guid("4d2d02f4-da33-48eb-bb84-ef7868505b29"),
                            Name = "BNS Container AS"
                        });
                });

            modelBuilder.Entity("ReenWise.Domain.Models.Mirror.Model", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasMaxLength(128);

                    b.Property<string>("Attachment")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(512)")
                        .HasMaxLength(512);

                    b.Property<float?>("HHeight")
                        .HasColumnType("real");

                    b.Property<float?>("Length")
                        .HasColumnType("real");

                    b.Property<Guid?>("ManufactorerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ManufacturerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(32)")
                        .HasMaxLength(32);

                    b.Property<float?>("Volume")
                        .HasColumnType("real");

                    b.Property<float?>("Weight")
                        .HasColumnType("real");

                    b.Property<float?>("Width")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Models");

                    b.HasData(
                        new
                        {
                            Id = new Guid("60a7e454-e90e-42f0-8b3d-700906fe0d10"),
                            Description = "B3",
                            Name = "DAJLJA C-05L-L",
                            SerialNumber = "MUM030887"
                        },
                        new
                        {
                            Id = new Guid("19b1c2ab-78a3-48c1-88e3-e343345d7181"),
                            Description = "C Estetisk stygg",
                            Name = "EAARST C-10L",
                            SerialNumber = "MUM030467"
                        },
                        new
                        {
                            Id = new Guid("315a5a1f-d5ea-4056-896a-f48773513a16"),
                            Description = "C Estetisk stygg",
                            Name = "EABXEL C-10L",
                            SerialNumber = "MUM030764"
                        },
                        new
                        {
                            Id = new Guid("394635d7-e5a6-49bd-afbc-2d8b0df0790f"),
                            Description = "B Estetisk stygg",
                            Name = "EACHRX C-08CL",
                            SerialNumber = "MUM030719"
                        },
                        new
                        {
                            Id = new Guid("21f1c05d-87f9-4ac3-89f7-cc0fbd146936"),
                            Description = "B Estetisk stygg",
                            Name = "EADRBA C-08CL",
                            SerialNumber = "MUM030746"
                        },
                        new
                        {
                            Id = new Guid("d149c72e-a50f-4918-8827-8c127b816517"),
                            Description = "B Fin",
                            Name = "EAEATJ C-22K",
                            SerialNumber = "MUM029340"
                        },
                        new
                        {
                            Id = new Guid("906603ac-ba24-4113-a2b1-800998376ae4"),
                            Description = "A Fin",
                            Name = "EAGUUU C-08CL",
                            SerialNumber = "MUM030683"
                        },
                        new
                        {
                            Id = new Guid("ca2aff1b-4c2e-4788-8f6d-958cbd40d64b"),
                            Description = "C Estetisk stygg",
                            Name = "EAHBYT C-10CL",
                            SerialNumber = "MUM030741"
                        },
                        new
                        {
                            Id = new Guid("d574adbc-a243-4bc1-8d79-a22a23208639"),
                            Description = "A Fin",
                            Name = "EAJFGU C-10LL",
                            SerialNumber = "MUM029330"
                        },
                        new
                        {
                            Id = new Guid("320a6d93-bf16-4b02-8f2e-78cee74c15e6"),
                            Description = "C Estetisk stygg",
                            Name = "EAKNKF C-10CL",
                            SerialNumber = "MUM030743"
                        },
                        new
                        {
                            Id = new Guid("ae36990b-7b26-4c95-8165-5bce8045e500"),
                            Description = "C Estetisk stygg",
                            Name = "EALUNJ C-10L",
                            SerialNumber = "MUM030509"
                        },
                        new
                        {
                            Id = new Guid("9d685eec-54e8-45de-9c3a-acb4743a1fa6"),
                            Description = "C Estetisk stygg",
                            Name = "EANVZX C-22K",
                            SerialNumber = "MUM030724"
                        });
                });

            modelBuilder.Entity("ReenWise.Domain.Models.Mirror.OdoMeter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasMaxLength(128);

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("OdoMeters");
                });

            modelBuilder.Entity("ReenWise.Domain.Models.Mirror.OperatingHours", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasMaxLength(128);

                    b.Property<int>("Hours")
                        .HasColumnType("int");

                    b.Property<bool>("UnitDriven")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("OperatingHours");
                });

            modelBuilder.Entity("ReenWise.Domain.Models.Mirror.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.ToTable("Organizations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("040c6370-6bad-4be7-814f-8d13c54e648d"),
                            Name = "Norsk Gjenvinning AS"
                        },
                        new
                        {
                            Id = new Guid("f92b51ad-543a-4cee-bfd8-a5aa39a708b9"),
                            Name = "SmartContainer AS"
                        });
                });

            modelBuilder.Entity("ReenWise.Domain.Models.Mirror.Temperature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasMaxLength(128);

                    b.Property<Guid?>("EquipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.Property<Guid?>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Temperatures");
                });

            modelBuilder.Entity("ReenWise.Domain.Models.Mirror.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasMaxLength(128);

                    b.Property<string>("Health")
                        .HasColumnType("nvarchar(32)")
                        .HasMaxLength(32);

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(32)")
                        .HasMaxLength(32);

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(32)")
                        .HasMaxLength(32);

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(32)")
                        .HasMaxLength(32);

                    b.HasKey("Id");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("ReenWise.Domain.Models.Mirror.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasMaxLength(128);

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<float?>("Co2Emissions")
                        .HasColumnType("real");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(32)")
                        .HasMaxLength(32);

                    b.Property<string>("CommercialClass")
                        .HasColumnType("nvarchar(32)")
                        .HasMaxLength(32);

                    b.Property<Guid?>("DriverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float?>("EngineSize")
                        .HasColumnType("real");

                    b.Property<string>("FuelType")
                        .HasColumnType("nvarchar(32)")
                        .HasMaxLength(32);

                    b.Property<Guid>("LicensePlateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ManufacturerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(1024)")
                        .HasMaxLength(1024);

                    b.Property<Guid?>("OdoMeterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("LicensePlateId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("ModelId");

                    b.HasIndex("OdoMeterId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("UnitId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("ReenWise.Domain.Models.Mirror.Driver", b =>
                {
                    b.HasOne("ReenWise.Domain.Models.Mirror.Organization", "Organization")
                        .WithMany("Drivers")
                        .HasForeignKey("OrganizationId");
                });

            modelBuilder.Entity("ReenWise.Domain.Models.Mirror.Equipment", b =>
                {
                    b.HasOne("ReenWise.Domain.Models.Mirror.OperatingHours", "InitialOperatingHours")
                        .WithMany()
                        .HasForeignKey("InitialOperatingHoursId");

                    b.HasOne("ReenWise.Domain.Models.Mirror.Manufacturer", null)
                        .WithMany("Equipments")
                        .HasForeignKey("ManufacturerId");

                    b.HasOne("ReenWise.Domain.Models.Mirror.Model", "Model")
                        .WithMany("Equipments")
                        .HasForeignKey("ModelId");

                    b.HasOne("ReenWise.Domain.Models.Mirror.OperatingHours", "OperatingHours")
                        .WithMany()
                        .HasForeignKey("OperatingHoursId");

                    b.HasOne("ReenWise.Domain.Models.Mirror.Organization", "Organization")
                        .WithMany("Equipments")
                        .HasForeignKey("OrganizationId");

                    b.HasOne("ReenWise.Domain.Models.Mirror.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId");
                });

            modelBuilder.Entity("ReenWise.Domain.Models.Mirror.Location", b =>
                {
                    b.HasOne("ReenWise.Domain.Models.Mirror.Equipment", null)
                        .WithMany("Locations")
                        .HasForeignKey("EquipmentId");

                    b.HasOne("ReenWise.Domain.Models.Mirror.Vehicle", null)
                        .WithMany("Locations")
                        .HasForeignKey("VehicleId");
                });

            modelBuilder.Entity("ReenWise.Domain.Models.Mirror.Model", b =>
                {
                    b.HasOne("ReenWise.Domain.Models.Mirror.Manufacturer", "Manufacturer")
                        .WithMany("Models")
                        .HasForeignKey("ManufacturerId");
                });

            modelBuilder.Entity("ReenWise.Domain.Models.Mirror.Temperature", b =>
                {
                    b.HasOne("ReenWise.Domain.Models.Mirror.Equipment", null)
                        .WithMany("Temperatures")
                        .HasForeignKey("EquipmentId");

                    b.HasOne("ReenWise.Domain.Models.Mirror.Vehicle", null)
                        .WithMany("Temperatures")
                        .HasForeignKey("VehicleId");
                });

            modelBuilder.Entity("ReenWise.Domain.Models.Mirror.Vehicle", b =>
                {
                    b.HasOne("ReenWise.Domain.Models.Mirror.Driver", "Driver")
                        .WithMany("Vehicles")
                        .HasForeignKey("DriverId");

                    b.HasOne("ReenWise.Domain.Models.Mirror.LicensePlate", "LicensePlate")
                        .WithMany()
                        .HasForeignKey("LicensePlateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReenWise.Domain.Models.Mirror.Manufacturer", null)
                        .WithMany("Vehicles")
                        .HasForeignKey("ManufacturerId");

                    b.HasOne("ReenWise.Domain.Models.Mirror.Model", "Model")
                        .WithMany("Vehicles")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReenWise.Domain.Models.Mirror.OdoMeter", "OdoMeter")
                        .WithMany()
                        .HasForeignKey("OdoMeterId");

                    b.HasOne("ReenWise.Domain.Models.Mirror.Organization", "Organization")
                        .WithMany("Vehicles")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReenWise.Domain.Models.Mirror.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId");
                });
#pragma warning restore 612, 618
        }
    }
}
